### ISSUE TITLE
Show external address in rest endpoint

### ISSUE THREAD

**Issue by polarker** [alephium/alephium#458]

**Comment by BlankerL** [comment]
Hello, I submitted this problem in Discord [here](https://discord.com/channels/747741246667227157/883355707146141737/918585859475902535), and I found that the external address in the "user.conf" could be obtained from endpoint `/info/node` rather than `/info/self-clique`. I don't think it should be a problem anymore.

**Comment by polarker** [comment]
Yes, it's added now. Thanks for the reminder!
